language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
      - snapd
install:
  - echo "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDODNxVXQyS2owUEZCOW1QMWNnQVpyMTdLbkkvQ0t3RG5mYmErQTBtTkowQ0dCakd4cFB6TzlMcDRDT01nc2VnUzF2MVpXdU4yTFVJdDd2SExBOVBoZGZrVHdsUGJoa1dqRUtxbytMM095MU1CZnV5aTAza05MYmZRMGc1eGtveXdBQ2ZPK2Rvd3RRaWNyOUZNT1duKzlBaE04R1JQTXFIYlpEUEhYeTJWLzRIUXhZRW1RNm9NNlh5YldrcEpQUjluWGZObllLcHNrd0NUYWdGSTNVeGlWeTk1YzlxNmQvMzlmUXViU05MN0pmZFlvM00zdlpFeVJVTUVRRXJDa01vWFMxK2lMWDNIcUVqYkYyWGJ1bVJnV0llNERINnlHS0ZzK1A2c01JMHRiVjkyTno5OXNENmxkQ1BSQVBjTlB3ZTVBU1RQS0RSc255b2xWZUhFalU0VDkgbWFjdXNlckBNYWNzLU1hY0Jvb2stUHJvLmxvY2FsCg==" | base64 -d >> $HOME/.ssh/known_hosts
  - sudo snap install doctl
  - yarn --frozen-lockfile
before_script:
  - psql -c 'create database babylon_api_test;' -U postgres
script:
  - yarn lint
  - yarn test
services:
  - postgresql
deploy:
  # Build Docker container and push to Docker Hub
  # Pull into DigitalOcean container and start
  provider: script
  script: bash deploy.sh
  on:
    branch: master